[package]
name = "reboot-pc-daemon"
version = "0.2.0"
authors = ["Gavyn Riebau <gavyn.riebau@readify.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
system_shutdown = "3.0.0"